"""Supermarket Together Türkçe yama kurucusu.

Bu dosya kaynak olarak çalıştırılabilir ve PyInstaller ile tek EXE olarak
paketlenebilir. Oyun dosyalarına dokunmadan önce üzerine yazılacak mevcut
 dosyaları tarih damgalı bir klasöre yedekler.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import threading
import tkinter as tk
from tkinter import filedialog, messagebox
from typing import Callable

VERSION = "12.27.4-fixed.1"
GAME_EXE = "Supermarket Together.exe"
APP_ID = "2709570"
APP_TITLE = "Supermarket Together — Türkçe Yama"

CONFIG_UPDATES = {
    ("Files", "Directory"): r"Translation\{Lang}\Text",
    ("Files", "OutputFile"): r"Translation\{Lang}\Text\_AutoGeneratedTranslations.txt",
    ("Files", "SubstitutionFile"): r"Translation\{Lang}\Text\_Substitutions.txt",
    ("Files", "PreprocessorsFile"): r"Translation\{Lang}\Text\_Preprocessors.txt",
    ("Files", "PostprocessorsFile"): r"Translation\{Lang}\Text\_Postprocessors.txt",
    ("TextFrameworks", "EnableTextMeshPro"): "True",
    ("TextFrameworks", "EnableUIElements"): "True",
    ("Behaviour", "EnableSilentMode"): "True",
    ("Debug", "EnableLog"): "False",
    ("Migrations", "Tag"): "5.6.2",
}


def resource_dir() -> Path:
    """PyInstaller içindeki veya kaynak ağacındaki mod_data dizini."""
    base = Path(getattr(sys, "_MEIPASS", Path(__file__).resolve().parent))
    return base / "mod_data"


def is_game_running() -> bool:
    if os.name != "nt":
        return False
    try:
        result = subprocess.run(
            ["tasklist", "/FI", f"IMAGENAME eq {GAME_EXE}"],
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="ignore",
            check=False,
            creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
        )
        return GAME_EXE.lower() in result.stdout.lower()
    except OSError:
        return False


def _steam_registry_paths() -> list[Path]:
    if os.name != "nt":
        return []
    try:
        import winreg
    except ImportError:
        return []

    found: list[Path] = []
    locations = (
        (winreg.HKEY_CURRENT_USER, r"Software\Valve\Steam", "SteamPath"),
        (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\WOW6432Node\Valve\Steam", "InstallPath"),
        (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Valve\Steam", "InstallPath"),
    )
    for hive, key_name, value_name in locations:
        try:
            with winreg.OpenKey(hive, key_name) as key:
                value, _ = winreg.QueryValueEx(key, value_name)
            found.append(Path(value))
        except OSError:
            continue
    return found


def parse_libraryfolders(vdf: Path) -> list[Path]:
    try:
        text = vdf.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return []
    return [Path(value.replace(r"\\", "\\")) for value in re.findall(r'"path"\s+"([^"]+)"', text)]


def find_game_path() -> Path | None:
    candidates: list[Path] = []
    for steam in _steam_registry_paths():
        candidates.append(steam)
        candidates.extend(parse_libraryfolders(steam / "steamapps" / "libraryfolders.vdf"))

    for letter in "CDEFGHIJKLMNOPQRSTUVWXYZ":
        root = Path(f"{letter}:/")
        candidates.extend((root / "SteamLibrary", root / "Program Files (x86)" / "Steam"))

    seen: set[str] = set()
    for library in candidates:
        key = str(library).lower()
        if key in seen:
            continue
        seen.add(key)
        game = library / "steamapps" / "common" / "Supermarket Together"
        if (game / GAME_EXE).is_file():
            return game
    return None


def validate_game_path(game_dir: Path) -> None:
    if not game_dir.is_dir() or not (game_dir / GAME_EXE).is_file():
        raise ValueError(f"Geçersiz oyun klasörü: {GAME_EXE} bulunamadı.")


def translation_count(game_dir: Path) -> int:
    target = game_dir / "BepInEx" / "Translation" / "tr" / "Text" / "_AutoGeneratedTranslations.txt"
    if not target.is_file():
        return 0
    text = target.read_text(encoding="utf-8-sig", errors="replace")
    return sum(1 for line in text.splitlines() if "=" in line and not line.lstrip().startswith("//"))


def update_ini(path: Path, updates: dict[tuple[str, str], str] = CONFIG_UPDATES) -> None:
    """INI biçimini/yorumları koruyarak gerekli XUnity değerlerini ayarla."""
    text = path.read_text(encoding="utf-8-sig", errors="replace") if path.exists() else ""
    lines = text.splitlines()
    found: set[tuple[str, str]] = set()
    section = ""
    output: list[str] = []

    for line in lines:
        stripped = line.strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            section = stripped[1:-1]
            output.append(line)
            continue
        if "=" in line and not stripped.startswith(("#", ";")):
            key = line.split("=", 1)[0].strip()
            pair = (section, key)
            if pair in updates:
                output.append(f"{key}={updates[pair]}")
                found.add(pair)
                continue
        output.append(line)

    missing = [(pair, value) for pair, value in updates.items() if pair not in found]
    for wanted_section in dict.fromkeys(pair[0] for pair, _ in missing):
        if output and output[-1] != "":
            output.append("")
        output.append(f"[{wanted_section}]")
        for (section_name, key), value in missing:
            if section_name == wanted_section:
                output.append(f"{key}={value}")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(output).rstrip() + "\n", encoding="utf-8")


def payload_files(data_dir: Path) -> list[Path]:
    if not data_dir.is_dir():
        raise FileNotFoundError("Kurulum verileri (mod_data) bulunamadı.")
    return sorted(path for path in data_dir.rglob("*") if path.is_file())


def backup_overwritten_files(game_dir: Path, files: list[Path], data_dir: Path) -> Path | None:
    existing = [(src, game_dir / src.relative_to(data_dir)) for src in files]
    existing = [(src, dst) for src, dst in existing if dst.is_file()]
    if not existing:
        return None

    stamp = dt.datetime.now().strftime("%Y%m%d-%H%M%S")
    backup = game_dir / "TR_Yama_Yedek" / stamp
    for _, dst in existing:
        rel = dst.relative_to(game_dir)
        target = backup / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(dst, target)
    return backup


def install_patch(
    game_dir: Path,
    data_dir: Path | None = None,
    *,
    make_backup: bool = True,
    check_process: bool = True,
    progress: Callable[[int, int], None] | None = None,
    log: Callable[[str], None] | None = None,
) -> dict[str, object]:
    game_dir = game_dir.resolve()
    data_dir = (data_dir or resource_dir()).resolve()
    validate_game_path(game_dir)
    if check_process and is_game_running():
        raise RuntimeError("Oyun açık. Kurulumdan önce Supermarket Together'ı kapatın.")

    files = payload_files(data_dir)
    if not files:
        raise FileNotFoundError("Kurulum paketi boş.")

    backup = backup_overwritten_files(game_dir, files, data_dir) if make_backup else None
    if backup and log:
        log(f"Yedek: {backup}")

    for index, source in enumerate(files, 1):
        relative = source.relative_to(data_dir)
        target = game_dir / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, target)
        if progress:
            progress(index, len(files))

    config = game_dir / "BepInEx" / "config" / "AutoTranslatorConfig.ini"
    update_ini(config)

    version_file = game_dir / "BepInEx" / "Translation" / "tr" / ".tr_version"
    version_file.parent.mkdir(parents=True, exist_ok=True)
    version_file.write_text(VERSION + "\n", encoding="utf-8")

    count = translation_count(game_dir)
    nested = game_dir / "BepInEx" / "BepInEx" / "Translation"
    if count < 1600:
        raise RuntimeError(f"Çeviri doğrulaması başarısız: yalnızca {count} satır bulundu.")
    if nested.exists():
        shutil.rmtree(nested)

    manifest = {
        "name": APP_TITLE,
        "version": VERSION,
        "upstream_translation_version": "12.27.4",
        "xunity_version": "5.6.2",
        "installed_at": dt.datetime.now(dt.timezone.utc).isoformat(),
        "translation_pairs": count,
        "payload_files": len(files),
        "backup": str(backup) if backup else None,
    }
    manifest_path = game_dir / "BepInEx" / "Translation" / "tr" / "installation.json"
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    if log:
        log(f"{len(files)} dosya kuruldu, {count} çeviri doğrulandı.")
    return manifest


class InstallerApp:
    BG = "#0c0d10"
    CARD = "#17191f"
    TEXT = "#f2f3f5"
    MUTED = "#9ca3af"
    ACCENT = "#e11d48"
    SUCCESS = "#22c55e"

    def __init__(self, root: tk.Tk) -> None:
        self.root = root
        root.title(f"{APP_TITLE} v{VERSION}")
        root.geometry("760x520")
        root.minsize(700, 480)
        root.configure(bg=self.BG)

        self.path_var = tk.StringVar(value=str(find_game_path() or ""))
        self.status_var = tk.StringVar(value="Kuruluma hazır")

        tk.Label(root, text="SUPERMARKET TOGETHER", bg=self.BG, fg=self.ACCENT,
                 font=("Segoe UI", 11, "bold")).pack(anchor="w", padx=34, pady=(28, 2))
        tk.Label(root, text="Türkçe Yama", bg=self.BG, fg=self.TEXT,
                 font=("Segoe UI", 28, "bold")).pack(anchor="w", padx=32)
        tk.Label(root, text=f"Uyumluluk sürümü {VERSION} · XUnity AutoTranslator 5.6.2",
                 bg=self.BG, fg=self.MUTED, font=("Segoe UI", 10)).pack(anchor="w", padx=34, pady=(2, 24))

        card = tk.Frame(root, bg=self.CARD, highlightbackground="#2b2f38", highlightthickness=1)
        card.pack(fill="both", expand=True, padx=32, pady=(0, 24))

        tk.Label(card, text="Oyun klasörü", bg=self.CARD, fg=self.TEXT,
                 font=("Segoe UI", 10, "bold")).pack(anchor="w", padx=22, pady=(20, 7))
        row = tk.Frame(card, bg=self.CARD)
        row.pack(fill="x", padx=22)
        self.entry = tk.Entry(row, textvariable=self.path_var, bg="#0f1115", fg=self.TEXT,
                              insertbackground=self.TEXT, relief="flat", font=("Segoe UI", 10))
        self.entry.pack(side="left", fill="x", expand=True, ipady=9)
        tk.Button(row, text="Gözat", command=self.browse, bg="#2b2f38", fg=self.TEXT,
                  activebackground="#3a3f49", activeforeground=self.TEXT, relief="flat",
                  cursor="hand2", padx=18, pady=8).pack(side="left", padx=(10, 0))

        self.progress = tk.DoubleVar(value=0)
        self.bar = tk.Scale(card, variable=self.progress, from_=0, to=100, orient="horizontal",
                            showvalue=False, bg=self.CARD, troughcolor="#252832", fg=self.ACCENT,
                            highlightthickness=0, state="disabled")
        self.bar.pack(fill="x", padx=20, pady=(22, 4))

        tk.Label(card, textvariable=self.status_var, bg=self.CARD, fg=self.MUTED,
                 font=("Segoe UI", 9)).pack(anchor="w", padx=22)
        tk.Label(card, text="Mevcut dosyalar kurulumdan önce otomatik yedeklenir.",
                 bg=self.CARD, fg=self.MUTED, font=("Segoe UI", 9)).pack(anchor="w", padx=22, pady=(8, 15))

        self.install_button = tk.Button(card, text="TÜRKÇE YAMAYI KUR", command=self.start,
                                        bg=self.ACCENT, fg="white", activebackground="#be123c",
                                        activeforeground="white", relief="flat", cursor="hand2",
                                        font=("Segoe UI", 11, "bold"), pady=12)
        self.install_button.pack(fill="x", padx=22, pady=(0, 22))

    def browse(self) -> None:
        selected = filedialog.askdirectory(title="Supermarket Together klasörünü seçin")
        if selected:
            self.path_var.set(selected)

    def start(self) -> None:
        self.install_button.configure(state="disabled")
        self.status_var.set("Dosyalar kontrol ediliyor…")
        self.progress.set(0)
        threading.Thread(target=self._worker, daemon=True).start()

    def _worker(self) -> None:
        try:
            manifest = install_patch(
                Path(self.path_var.get().strip()),
                progress=lambda done, total: self.root.after(0, self.progress.set, done * 100 / total),
                log=lambda text: self.root.after(0, self.status_var.set, text),
            )
            count = manifest["translation_pairs"]
            self.root.after(0, self._finish, True, f"Kurulum tamamlandı. {count} çeviri hazır.")
        except Exception as exc:
            self.root.after(0, self._finish, False, str(exc))

    def _finish(self, success: bool, text: str) -> None:
        self.install_button.configure(state="normal")
        self.status_var.set(text)
        if success:
            self.progress.set(100)
            messagebox.showinfo(APP_TITLE, text + "\n\nOyunun dili İngilizce kalmalıdır; yama metinleri Türkçeye çevirir.")
        else:
            messagebox.showerror(APP_TITLE, text)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=APP_TITLE)
    parser.add_argument("--install-dir", type=Path, help="Oyunun kurulu olduğu klasör")
    parser.add_argument("--quiet", action="store_true", help="GUI açmadan kur")
    parser.add_argument("--no-backup", action="store_true", help="Yedek oluşturma")
    parser.add_argument("--skip-process-check", action="store_true", help=argparse.SUPPRESS)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.quiet:
        if not args.install_dir:
            print("HATA: --quiet ile --install-dir zorunludur.", file=sys.stderr)
            return 2
        try:
            manifest = install_patch(
                args.install_dir,
                make_backup=not args.no_backup,
                check_process=not args.skip_process_check,
                log=print,
            )
            print(json.dumps(manifest, ensure_ascii=False))
            return 0
        except Exception as exc:
            print(f"HATA: {exc}", file=sys.stderr)
            return 1

    root = tk.Tk()
    InstallerApp(root)
    root.mainloop()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
